### ISSUE TITLE
Allocate this towards the next upgrade audit? (Seraphis or similar)

### ISSUE THREAD

**Issue by johnr365** [plowsof/scrape_ccs_fr#1]
Presumably these excess CCS funds can be put to good use somehow.

One such opportunity is getting some extra eyes  on the Seraphis (or similar) code when it comes time. Specifically I mean at least one third party audit.

Of course, there may be better suggestions for where to put the funds.

**Comment by plowsof** [comment]
Thanks for finding this repo john! we can start discussing this as a community now. its only been briefly discussed, the more suggestions the better!

**Comment by johnr365** [comment]
Sounds good RE discussing as a community! Agree RE more suggestions the better. Something good will come out of it.

**Comment by plowsof** [comment]
A few others offered their suggestions at the bottom of the meeting logs at https://github.com/monero-project/meta/issues/810 

It seems a combination of 'all of the above' would work i.e. 'rolling over' for persons with regular ccs' ... a period of time for historic claims to be made .... send the remaining funds to the general fund minus some 'gas' fees (with the intention of being used for audits/reviews/things vital to the monero project)

**Comment by plowsof** [comment]
will move the discussion to #2
